manifest:
  group-filter:
  - -babblesim
  projects:
  - name: zmk
    url: https://github.com/edward-tecky/zmk
    revision: 7c61a5496910a48d2db2d6abdb249950b791ca9a
    west-commands: scripts/west-commands.yml
  - name: zephyr
    url: https://github.com/zmkfirmware/zephyr
    revision: 9df4b12b5af3438a8b9d7a33780dc3b3b2f516c1
    clone-depth: 1
    west-commands: scripts/west-commands.yml
  - name: hal_stm32
    url: https://github.com/zmkfirmware/hal_stm32
    revision: 4fcc3a3f32abe1c4cb76d9d1cef967728dd03908
    path: modules/hal/stm32
    groups:
    - hal
  - name: lvgl
    url: https://github.com/zmkfirmware/lvgl
    revision: f1db87ee98f1810328a8419572fa42a3b5f352ae
    path: modules/lib/gui/lvgl
  - name: zmk-studio-messages
    url: https://github.com/zmkfirmware/zmk-studio-messages
    revision: 6cb4c283e76209d59c45fbcb218800cd19e9339d
    path: modules/msgs/zmk-studio-messages
  - name: canopennode
    url: https://github.com/zephyrproject-rtos/canopennode
    revision: dec12fa3f0d790cafa8414a4c2930ea71ab72ffd
    path: modules/lib/canopennode
    groups:
    - optional
  - name: chre
    url: https://github.com/zephyrproject-rtos/chre
    revision: 3b32c76efee705af146124fb4190f71be5a4e36e
    path: modules/lib/chre
    groups:
    - optional
  - name: lz4
    url: https://github.com/zephyrproject-rtos/lz4
    revision: 11b8a1e22fa651b524494e55d22b69d3d9cebcfd
    path: modules/lib/lz4
    groups:
    - optional
  - name: nanopb
    url: https://github.com/zephyrproject-rtos/nanopb
    revision: 7307ce399b81ddcb3c3a5dc862c52d4754328d38
    path: modules/lib/nanopb
    groups:
    - optional
  - name: psa-arch-tests
    url: https://github.com/zephyrproject-rtos/psa-arch-tests
    revision: 2cadb02a72eacda7042505dcbdd492371e8ce024
    path: modules/tee/tf-m/psa-arch-tests
    groups:
    - optional
  - name: sof
    url: https://github.com/zephyrproject-rtos/sof
    revision: bc08c9c606324cfba0c104f4ffaf5dd456cb11d6
    path: modules/audio/sof
    groups:
    - optional
  - name: tf-m-tests
    url: https://github.com/zephyrproject-rtos/tf-m-tests
    revision: 502ea90105ee18f20c78f710e2ba2ded0fc0756e
    path: modules/tee/tf-m/tf-m-tests
    groups:
    - optional
  - name: tflite-micro
    url: https://github.com/zephyrproject-rtos/tflite-micro
    revision: 8d404de73acf7687831e16d88e86e4f73cfddf8e
    path: optional/modules/lib/tflite-micro
    groups:
    - optional
  - name: thrift
    url: https://github.com/zephyrproject-rtos/thrift
    revision: 10023645a0e6cb7ce23fcd7fd3dbac9f18df6234
    path: optional/modules/lib/thrift
    groups:
    - optional
  - name: zephyr-lang-rust
    url: https://github.com/zephyrproject-rtos/zephyr-lang-rust
    revision: 37dc7fac3fb0372bc0e78e022bef87fcce68c48d
    path: modules/lang/rust
    groups:
    - optional
  - name: zscilib
    url: https://github.com/zephyrproject-rtos/zscilib
    revision: ee1b287d9dd07208d2cc52284240ac25bb66eae3
    path: modules/lib/zscilib
    groups:
    - optional
  - name: acpica
    url: https://github.com/zephyrproject-rtos/acpica
    revision: 8d24867bc9c9d81c81eeac59391cda59333affd4
    path: modules/lib/acpica
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis
    revision: d1b8b20b6278615b00e136374540eb1c00dcabe7
    path: modules/hal/cmsis
    groups:
    - hal
  - name: cmsis-dsp
    url: https://github.com/zephyrproject-rtos/cmsis-dsp
    revision: d80a49b2bb186317dc1db4ac88da49c0ab77e6e7
    path: modules/lib/cmsis-dsp
  - name: cmsis-nn
    url: https://github.com/zephyrproject-rtos/cmsis-nn
    revision: e9328d612ea3ea7d0d210d3ac16ea8667c01abdd
    path: modules/lib/cmsis-nn
  - name: cmsis_6
    url: https://github.com/zephyrproject-rtos/CMSIS_6
    revision: 783317a3072554acbac86cca2ff24928cbf98d30
    path: modules/lib/cmsis_6
  - name: fatfs
    url: https://github.com/zephyrproject-rtos/fatfs
    revision: 16245c7c41d2b79e74984f49b5202551786b8a9b
    path: modules/fs/fatfs
    groups:
    - fs
  - name: hal_adi
    url: https://github.com/zephyrproject-rtos/hal_adi
    revision: 633fcecf3717aaa22079cf6121627a879f24df51
    path: modules/hal/adi
    groups:
    - hal
  - name: hal_ambiq
    url: https://github.com/zephyrproject-rtos/hal_ambiq
    revision: 87a188b91aca22ce3ce7deb4a1cbf7780d784673
    path: modules/hal/ambiq
    groups:
    - hal
  - name: hal_atmel
    url: https://github.com/zephyrproject-rtos/hal_atmel
    revision: da767444cce3c1d9ccd6b8a35fd7c67dc82d489c
    path: modules/hal/atmel
    groups:
    - hal
  - name: hal_espressif
    url: https://github.com/zephyrproject-rtos/hal_espressif
    revision: 202c59552dc98e5cd02386313e1977ecb17a131f
    path: modules/hal/espressif
    west-commands: west/west-commands.yml
    groups:
    - hal
  - name: hal_ethos_u
    url: https://github.com/zephyrproject-rtos/hal_ethos_u
    revision: 50ddffca1cc700112f25ad9bc077915a0355ee5d
    path: modules/hal/ethos_u
    groups:
    - hal
  - name: hal_gigadevice
    url: https://github.com/zephyrproject-rtos/hal_gigadevice
    revision: 2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3
    path: modules/hal/gigadevice
    groups:
    - hal
  - name: hal_intel
    url: https://github.com/zephyrproject-rtos/hal_intel
    revision: 0355bb816263c54eed23c7781034447af5d8200c
    path: modules/hal/intel
    groups:
    - hal
  - name: hal_nordic
    url: https://github.com/zephyrproject-rtos/hal_nordic
    revision: 37ca068d7b013fb65a2acc9306bffa48a3e72839
    path: modules/hal/nordic
    groups:
    - hal
  - name: hal_nuvoton
    url: https://github.com/zephyrproject-rtos/hal_nuvoton
    revision: 466c3eed9c98453fb23953bf0e0427fea01924be
    path: modules/hal/nuvoton
    groups:
    - hal
  - name: hal_quicklogic
    url: https://github.com/zephyrproject-rtos/hal_quicklogic
    revision: bad894440fe72c814864798c8e3a76d13edffb6c
    path: modules/hal/quicklogic
    groups:
    - hal
  - name: hal_renesas
    url: https://github.com/zephyrproject-rtos/hal_renesas
    revision: 3204903bdc5eda6869a40363560a69369c8d0e22
    path: modules/hal/renesas
    groups:
    - hal
  - name: hal_rpi_pico
    url: https://github.com/zephyrproject-rtos/hal_rpi_pico
    revision: 7b57b24588797e6e7bf18b6bda168e6b96374264
    path: modules/hal/rpi_pico
    groups:
    - hal
  - name: hal_silabs
    url: https://github.com/zephyrproject-rtos/hal_silabs
    revision: 8a173e9e566a396a19d18da4661cb54ce098f268
    path: modules/hal/silabs
    groups:
    - hal
  - name: hal_tdk
    url: https://github.com/zephyrproject-rtos/hal_tdk
    revision: 6727477af1e46fa43878102489b9672a9d24e39f
    path: modules/hal/tdk
    groups:
    - hal
  - name: hal_telink
    url: https://github.com/zephyrproject-rtos/hal_telink
    revision: 4226c7fc17d5a34e557d026d428fc766191a0800
    path: modules/hal/telink
    groups:
    - hal
  - name: hal_wch
    url: https://github.com/zephyrproject-rtos/hal_wch
    revision: 1de9d3e406726702ce7cfc504509a02ecc463554
    path: modules/hal/wch
    groups:
    - hal
  - name: hal_wurthelektronik
    url: https://github.com/zephyrproject-rtos/hal_wurthelektronik
    revision: e3e2797b224fc48fdef1bc3e5a12a7c73108bba2
    path: modules/hal/wurthelektronik
    groups:
    - hal
  - name: hostap
    url: https://github.com/zephyrproject-rtos/hostap
    revision: 697fd2cf5cbbd0c5375fc34761b6a9d7489a67d2
    path: modules/lib/hostap
  - name: liblc3
    url: https://github.com/zephyrproject-rtos/liblc3
    revision: 48bbd3eacd36e99a57317a0a4867002e0b09e183
    path: modules/lib/liblc3
  - name: libmctp
    url: https://github.com/zephyrproject-rtos/libmctp
    revision: b97860e78998551af99931ece149eeffc538bdb1
    path: modules/lib/libmctp
  - name: libmetal
    url: https://github.com/zephyrproject-rtos/libmetal
    revision: 3e8781aae9d7285203118c05bc01d4eb0ca565a7
    path: modules/hal/libmetal
    groups:
    - hal
  - name: littlefs
    url: https://github.com/zephyrproject-rtos/littlefs
    revision: ed0531d59ee37f5fb2762bcf2fc8ba4efaf82656
    path: modules/fs/littlefs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls
    revision: 4952e1328529ee549d412b498ea71c54f30aa3b1
    path: modules/crypto/mbedtls
    groups:
    - crypto
  - name: mipi-sys-t
    url: https://github.com/zephyrproject-rtos/mipi-sys-t
    revision: 33e5c23cbedda5ba12dbe50c4baefb362a791001
    path: modules/debug/mipi-sys-t
    groups:
    - debug
  - name: nrf_hw_models
    url: https://github.com/zephyrproject-rtos/nrf_hw_models
    revision: 73a5d5827a94820be65b7d276d28173ec10bab9f
    path: modules/bsim_hw_models/nrf_hw_models
  - name: nrf_wifi
    url: https://github.com/zephyrproject-rtos/nrf_wifi
    revision: e35f707a782b7c4c0eb83a3b06ca4e6eb693f29f
    path: modules/lib/nrf_wifi
  - name: open-amp
    url: https://github.com/zephyrproject-rtos/open-amp
    revision: 52bb1783521c62c019451cee9b05b8eda9d7425f
    path: modules/lib/open-amp
  - name: percepio
    url: https://github.com/zephyrproject-rtos/percepio
    revision: 49e6dc202aa38c2a3edbafcc2dab85dec6aee973
    path: modules/debug/percepio
    groups:
    - debug
  - name: picolibc
    url: https://github.com/zephyrproject-rtos/picolibc
    revision: 82d62ed1ac55b4e34a12d0390aced2dc9af13fc9
    path: modules/lib/picolibc
  - name: segger
    url: https://github.com/zephyrproject-rtos/segger
    revision: cf56b1d9c80f81a26e2ac5727c9cf177116a4692
    path: modules/debug/segger
    groups:
    - debug
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: modules/crypto/tinycrypt
    groups:
    - crypto
  - name: trusted-firmware-a
    url: https://github.com/zephyrproject-rtos/trusted-firmware-a
    revision: 713ffbf96c5bcbdeab757423f10f73eb304eff07
    path: modules/tee/tf-a/trusted-firmware-a
    groups:
    - tee
  - name: uoscore-uedhoc
    url: https://github.com/zephyrproject-rtos/uoscore-uedhoc
    revision: 54abc109c9c0adfd53c70077744c14e454f04f4a
    path: modules/lib/uoscore-uedhoc
  - name: zcbor
    url: https://github.com/zephyrproject-rtos/zcbor
    revision: 9b07780aca6fb21f82a241ba386ad9b379809337
    path: modules/lib/zcbor
  self:
    path: config
