name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-user-config-pinned.yml
    with:
      source_ref: ${{ github.sha }}
