name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml

jobs:
  draw:
    # keymap-drawer main resolved and audited on 2026-07-29.
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@3a4ca7e060a54ba700d3e7b6a43cb0b9cec347d2
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
